### Register
POST http://localhost:3000/api/usuarios/register
Content-Type: application/json

{
    "nombre":"jorge",
    "correo":"joreg@gmail.com",
    "contrasenna":"456",
    "idRol": "65f5cbfaf6eb3d011e1e2a50"
}

### Login
POST http://localhost:3000/api/usuarios/login
Content-Type: application/json

{
    "correo": "User00@email.com",
    "contrasenna":"456"
}

### ListaUsuarios
GET http://localhost:3000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2NvcnJlbyI6ImFkbWluMDBAZW1haWwuY29tIiwidXNlcl9yb2xlIjoxLCJpYXQiOjE3MTEyMjUyMjB9.P4yvRK0g0Y-1jxQDHsBLYsqC-3mTvjafuIlR7P4o0Ws

### DetalleUsuario
GET http://localhost:3000/api/users/65ff20ec4acb732a46d02417
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2NvcnJlbyI6ImFkbWluMDBAZW1haWwuY29tIiwidXNlcl9yb2xlIjoxLCJpYXQiOjE3MTEyMjUyMjB9.P4yvRK0g0Y-1jxQDHsBLYsqC-3mTvjafuIlR7P4o0Ws

### AgregarUsuario
POST http://localhost:3000/api/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2NvcnJlbyI6ImFkbWluMDBAZW1haWwuY29tIiwidXNlcl9yb2xlIjoxLCJpYXQiOjE3MTEyMjUyMjB9.P4yvRK0g0Y-1jxQDHsBLYsqC-3mTvjafuIlR7P4o0Ws

{
    "nombre":"userApi",
    "correo":"userApi@gmail.com",
    "contrasenna":"123",
    "idRol": "65f5cbfaf6eb3d011e1e2a50"
}

### ModificarUsuario
PUT http://localhost:3000/api/users/662058fe6822985c3d662a61
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2NvcnJlbyI6ImFkbWluMDBAZW1haWwuY29tIiwidXNlcl9yb2xlIjoxLCJpYXQiOjE3MTEyMjUyMjB9.P4yvRK0g0Y-1jxQDHsBLYsqC-3mTvjafuIlR7P4o0Ws
Content-Type: application/json

{
    "idRol": "65f5cbfaf6eb3d011e1e2a50"
}

### EliminarUsuario
DELETE http://localhost:3000/api/users/65f5e14f2136e8dfeab7ed2b
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2NvcnJlbyI6ImFkbWluMDBAZW1haWwuY29tIiwidXNlcl9yb2xlIjoxLCJpYXQiOjE3MTEyMjUyMjB9.P4yvRK0g0Y-1jxQDHsBLYsqC-3mTvjafuIlR7P4o0Ws